const TILE_SIZE=32,WORLD_WIDTH=8000,WORLD_HEIGHT=4800;
const MAP_LIBRARY_KEY='idlekin.prototype02.maps.v1',WORLD_STORAGE_KEY='idlekin.prototype03.world.v1',QUEST_STORAGE_KEY='idlekin.prototype04.quests.v1',PROJECT_STORAGE_KEY='idlekin.prototype05.monsters.v1',PLAYTEST_KEY='idlekin.playtest.payload.v1';
const SHEETS=['Tileset.png','Objects.png','Details.png','cave_entrance.png','chest.png','Clouds_in_tiles.png','Fairys.png','Flying_stone.png','key.png','Predator_plant.png','shinies.png','Spikes.png','stalactites.png'];
const BACKGROUNDS=['Full_bgx32.png','Skyx32.png','Clouds_x32.png','Flora2x32.png','Flora1x32.png'];
const ENEMIES=[
 {id:'slime',name:'Waldschleim',type:'Monster',level:[8,12],sprite:'Slime/idle.png',frame:156,hp:240,damage:18,armor:6,speed:1.4,xp:32,gold:[4,9],drops:[{name:'Schleimgel',chance:65},{name:'Mooskern',chance:8}]},
 {id:'rat',name:'Höhlenratte',type:'Monster',level:[3,6],sprite:'Rat/idle.png',frame:70,hp:90,damage:8,armor:2,speed:1,xp:14,gold:[1,4],drops:[{name:'Rattenschwanz',chance:35}]},
 {id:'bat',name:'Dämmerflügel',type:'Monster',level:[12,16],sprite:'Bat/fly.png',frame:87,hp:160,damage:24,armor:3,speed:.8,xp:45,gold:[6,12],drops:[{name:'Dämmerflügel',chance:18}]},
 {id:'mimic',name:'Truhenmimik',type:'Boss',level:[22,25],sprite:'Mimic/idle_transformed.png',frame:146,hp:2800,damage:85,armor:24,speed:1.8,xp:720,gold:[80,160],drops:[{name:'Mimikzahn',chance:100},{name:'Schatzschlüssel',chance:12}]}
];
const APPEARANCES=[{label:'Waldschleim',sprite:'Slime/idle.png',frame:156},{label:'Höhlenratte',sprite:'Rat/idle.png',frame:70},{label:'Dämmerflügel',sprite:'Bat/fly.png',frame:87},{label:'Truhenmimik',sprite:'Mimic/idle_transformed.png',frame:146}];
const viewport=document.querySelector('#viewport'),worldElement=document.querySelector('#world'),imageCache=new Map();
let project={version:1,source:'Keine Quelle',world:null,npcs:[],enemies:structuredClone(ENEMIES),spawns:[],animations:{}};
let selectedEnemyId='slime',selectedSpawnId=null,tool='select',zoom=.4,toastTimer=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const clone=value=>structuredClone(value);const mapWidth=s=>s.mapState.map.columns*TILE_SIZE;const mapHeight=s=>s.mapState.map.rows*TILE_SIZE;
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
function imageFrom(src){if(!imageCache.has(src))imageCache.set(src,new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src}));return imageCache.get(src)}
async function mapPreview(state,canvas){const width=state.map.columns*TILE_SIZE,height=state.map.rows*TILE_SIZE;canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.fillStyle='#111722';ctx.fillRect(0,0,width,height);if(state.map.background&&BACKGROUNDS.includes(state.map.background))try{ctx.drawImage(await imageFrom(`../../assets/tileset/PNG/Background/x32/${state.map.background}`),0,0,width,height)}catch{}for(const layer of state.layers||[]){if(layer.visible===false)continue;for(const p of layer.placements||[]){if(!SHEETS.includes(p.sheet))continue;try{const image=await imageFrom(`../../assets/tileset/PNG/${p.sheet}`);ctx.drawImage(image,p.sourceX*TILE_SIZE,p.sourceY*TILE_SIZE,p.width*TILE_SIZE,p.height*TILE_SIZE,p.x*TILE_SIZE,p.y*TILE_SIZE,p.width*TILE_SIZE,p.height*TILE_SIZE)}catch{}}}}
function spriteStyle(enemy){return `background-image:url('../../assets/enemy/Monsters%20Creatures%20Fantasy%202/${enemy.sprite}');background-size:auto 58px`}
function renderEnemyList(){$('#enemy-list').innerHTML=project.enemies.map(enemy=>`<button class="enemy-card ${enemy.type==='Boss'?'boss ':''}${enemy.id===selectedEnemyId?'active':''}" data-id="${enemy.id}"><span class="enemy-thumb"><i class="enemy-sprite" style="${spriteStyle(enemy)}"></i></span><span><strong>${enemy.name}</strong><span>${enemy.type} · Lv. ${enemy.level[0]}–${enemy.level[1]}</span></span><b>${project.spawns.filter(s=>s.enemyId===enemy.id).length}</b></button>`).join('');$$('.enemy-card').forEach(button=>button.onclick=()=>{selectedEnemyId=button.dataset.id;renderEnemyList();$('#placement-text').textContent=`${project.enemies.find(e=>e.id===selectedEnemyId).name} in einen Kartenabschnitt setzen`;renderInspector()})}
function createPortal(portal){const el=document.createElement('span');el.className='portal';Object.assign(el.style,{left:`${portal.x}px`,top:`${portal.y}px`});el.innerHTML=`<span class="portal-name">${portal.name}</span>`;return el}
function createNpc(npc){const el=document.createElement('span');el.className='npc-marker';el.style.setProperty('--sprite-x',`${-64*(Number(npc.sprite?.col)||0)}px`);el.style.setProperty('--sprite-y',`${-64*(Number(npc.sprite?.row)||0)}px`);Object.assign(el.style,{left:`${npc.x}px`,top:`${npc.y}px`});el.innerHTML=`<span class="npc-nameplate">${npc.name}</span>`;return el}
function createSpawn(spawn){
 const enemy=project.enemies.find(e=>e.id===spawn.enemyId)||project.enemies[0];
 const el=document.createElement('button');el.dataset.spawn=spawn.id;
 if(spawn.kind==='zone'){const size=Math.max(96,spawn.radius*2);el.className=`spawn-zone${spawn.id===selectedSpawnId?' selected':''}`;Object.assign(el.style,{left:`${spawn.x}px`,top:`${spawn.y}px`,width:`${size}px`,height:`${size}px`});el.innerHTML=`<span class="zone-count">${enemy.name} · max. ${spawn.max}</span>`}
 else{el.className=`spawn-marker ${enemy.type==='Boss'?'boss ':''}${spawn.id===selectedSpawnId?'selected':''}`;Object.assign(el.style,{left:`${spawn.x}px`,top:`${spawn.y}px`});el.innerHTML=`<i class="enemy-sprite" style="${spriteStyle(enemy)}"></i><span class="marker-name">${spawn.name}</span>`}
 el.onpointerdown=event=>{event.stopPropagation();if(tool==='erase'){project.spawns=project.spawns.filter(s=>s.id!==spawn.id);selectedSpawnId=null;markDirty();renderAll();toast('Platzierung gelöscht');return}selectedSpawnId=spawn.id;setTool('select');renderAll()};return el
}
function createSection(section){const el=document.createElement('article');el.className='section';el.dataset.id=section.id;Object.assign(el.style,{left:`${section.x}px`,top:`${section.y}px`,width:`${mapWidth(section)}px`,height:`${mapHeight(section)}px`});const canvas=document.createElement('canvas'),label=document.createElement('span');label.className='section-label';label.textContent=section.name;el.append(canvas,label);mapPreview(section.mapState,canvas);if($('#show-portals').checked)for(const portal of project.world.portals.filter(p=>p.sectionId===section.id))el.append(createPortal(portal));if($('#show-npcs').checked)for(const npc of project.npcs.filter(n=>n.sectionId===section.id))el.append(createNpc(npc));for(const spawn of project.spawns.filter(s=>s.sectionId===section.id))el.append(createSpawn(spawn));el.onpointerdown=event=>sectionPointer(event,section,el);return el}
function renderWorld(){worldElement.querySelectorAll('.section').forEach(el=>el.remove());$('#world-name').textContent=project.world?.name||'Keine Welt geladen';$('#empty-world').hidden=Boolean(project.world?.sections.length);if(project.world)for(const section of project.world.sections)worldElement.append(createSection(section));$('#status-source').textContent=`Quelle: ${project.source}`;$('#status-count').textContent=`${project.spawns.filter(s=>s.kind==='spawner').length} Spawner · ${project.spawns.filter(s=>s.kind==='zone').length} Zonen · ${project.npcs.length} NPCs`}
function localPoint(event,el,section){const rect=el.getBoundingClientRect();return{x:Math.round((event.clientX-rect.left)/rect.width*mapWidth(section)),y:Math.round((event.clientY-rect.top)/rect.height*mapHeight(section))}}
function sectionPointer(event,section,el){if(tool!=='monster'&&tool!=='zone')return;event.stopPropagation();const point=localPoint(event,el,section),enemy=project.enemies.find(e=>e.id===selectedEnemyId);project.spawns.push({id:`spawn-${Date.now()}`,kind:tool==='zone'?'zone':'spawner',enemyId:enemy.id,sectionId:section.id,x:point.x,y:point.y,name:`${enemy.name}-${tool==='zone'?'Zone':'Spawner'}`,max:enemy.type==='Boss'?1:6,respawn:enemy.type==='Boss'?300:20,radius:tool==='zone'?160:64,behavior:'Gebiet bewachen',aggro:288,returns:true});selectedSpawnId=project.spawns.at(-1).id;setTool('select');markDirty();renderAll();toast(`${enemy.name} platziert`)}
function markDirty(){$('#save-state').textContent='Nicht gespeichert'}
function bindValue(root,selector,event,callback){const el=root.querySelector(selector);if(el)el.addEventListener(event,()=>{callback(el);markDirty()})}
function renderSpawnPanel(){
 const root=$('#tab-spawn'),spawn=project.spawns.find(s=>s.id===selectedSpawnId);
 if(!spawn){root.innerHTML='<div class="nothing-selected"><strong>Kein Spawner ausgewählt</strong><span>Wähle einen Gegner links und platziere ihn mit M oder Z direkt auf einer geladenen Welt.</span></div>';return}
 const section=project.world?.sections.find(s=>s.id===spawn.sectionId);
 root.innerHTML=`<span class="type-badge">${spawn.kind==='zone'?'Monsterzone':'Spawner'}</span>
  <label>Name<input id="spawn-name" value="${spawn.name}"></label>
  <label>Gegnertyp<select id="spawn-enemy">${project.enemies.map(e=>`<option value="${e.id}" ${e.id===spawn.enemyId?'selected':''}>${e.name}</option>`).join('')}</select></label>
  <div class="form-grid"><label>Max. Gegner<input id="spawn-max" type="number" min="1" value="${spawn.max}"></label><label>Respawn (Sek.)<input id="spawn-respawn" type="number" min="1" value="${spawn.respawn}"></label></div>
  <label>Verhalten<select id="spawn-behavior">${['Gebiet bewachen','Patrouillieren','Spieler jagen','Friedlich bis Angriff'].map(v=>`<option ${v===spawn.behavior?'selected':''}>${v}</option>`).join('')}</select></label>
  <div class="form-grid"><label>Aggro-Radius (px)<input id="spawn-aggro" type="number" min="32" step="32" value="${spawn.aggro||288}"></label><label>Zonenradius (px)<input id="spawn-radius" type="number" min="32" step="32" value="${spawn.radius||64}"></label></div>
  <label class="check-row"><input id="spawn-return" type="checkbox" ${spawn.returns?'checked':''}> Nach Kampf zurückkehren</label>
  <div class="placement-card"><div><strong>${section?.name||'Unbekannter Abschnitt'}</strong><span>X ${spawn.x} · Y ${spawn.y}</span></div><button id="jump-spawn" class="small">Anzeigen</button></div>
  <button id="delete-spawn" class="danger wide">Platzierung löschen</button>`;
 bindValue(root,'#spawn-name','input',el=>spawn.name=el.value);bindValue(root,'#spawn-enemy','change',el=>spawn.enemyId=el.value);bindValue(root,'#spawn-max','change',el=>spawn.max=Math.max(1,Number(el.value)));bindValue(root,'#spawn-respawn','change',el=>spawn.respawn=Math.max(1,Number(el.value)));bindValue(root,'#spawn-behavior','change',el=>spawn.behavior=el.value);bindValue(root,'#spawn-aggro','change',el=>spawn.aggro=Number(el.value));bindValue(root,'#spawn-radius','change',el=>{spawn.radius=Number(el.value);renderWorld()});bindValue(root,'#spawn-return','change',el=>spawn.returns=el.checked);
 $('#jump-spawn').onclick=()=>{if(!section)return;viewport.scrollTo({left:(section.x+spawn.x)*zoom-viewport.clientWidth/2,top:(section.y+spawn.y)*zoom-viewport.clientHeight/2,behavior:'smooth'})};
 $('#delete-spawn').onclick=()=>{project.spawns=project.spawns.filter(s=>s.id!==spawn.id);selectedSpawnId=null;markDirty();renderAll();toast('Platzierung gelöscht')}
}
function renderEnemyPanel(){
 const root=$('#tab-enemy'),enemy=project.enemies.find(e=>e.id===selectedEnemyId);if(!enemy){root.innerHTML='<div class="nothing-selected">Kein Gegner ausgewählt.</div>';return}
 root.innerHTML=`<span class="type-badge ${enemy.type==='Boss'?'boss-badge':''}">${enemy.type}</span>
  <div class="appearance-grid">${APPEARANCES.map((a,i)=>`<button class="appearance ${a.sprite===enemy.sprite?'active':''}" data-appearance="${i}"><i class="enemy-sprite" style="${spriteStyle(a)}"></i><small>${a.label}</small></button>`).join('')}</div>
  <label>Name<input id="enemy-name" value="${enemy.name}"></label><label>Kategorie<select id="enemy-type"><option ${enemy.type==='Monster'?'selected':''}>Monster</option><option ${enemy.type==='Boss'?'selected':''}>Boss</option></select></label>
  <div class="form-grid"><label>Level von<input id="level-min" type="number" value="${enemy.level[0]}"></label><label>Level bis<input id="level-max" type="number" value="${enemy.level[1]}"></label><label>Leben<input id="enemy-hp" type="number" value="${enemy.hp}"></label><label>Schaden<input id="enemy-damage" type="number" value="${enemy.damage}"></label><label>Rüstung<input id="enemy-armor" type="number" value="${enemy.armor||0}"></label><label>Angriffstempo<input id="enemy-speed" type="number" step=".1" value="${enemy.speed||1}"></label></div>
  <div class="section-heading"><div><h3>Belohnungen</h3><p>Werden von Quests und Kampf verwendet.</p></div></div><div class="form-grid"><label>Erfahrung<input id="enemy-xp" type="number" value="${enemy.xp||0}"></label><label>Gold<input id="enemy-gold" value="${(enemy.gold||[0,0]).join('–')}"></label></div>
  <div class="section-heading"><div><h3>Drops</h3></div><button id="add-drop" class="small">+ Drop</button></div><div id="drops">${(enemy.drops||[]).map((d,i)=>`<div class="drop-row"><span>${d.name}</span><input data-drop="${i}" type="number" value="${d.chance}" title="Dropchance in Prozent"><button data-remove-drop="${i}" class="small danger">×</button></div>`).join('')}</div>`;
 $$('.appearance',root).forEach(button=>button.onclick=()=>{const a=APPEARANCES[Number(button.dataset.appearance)];enemy.sprite=a.sprite;enemy.frame=a.frame;markDirty();renderAll()});
 bindValue(root,'#enemy-name','input',el=>{enemy.name=el.value;renderEnemyList()});bindValue(root,'#enemy-type','change',el=>enemy.type=el.value);bindValue(root,'#level-min','change',el=>enemy.level[0]=Number(el.value));bindValue(root,'#level-max','change',el=>enemy.level[1]=Number(el.value));bindValue(root,'#enemy-hp','change',el=>enemy.hp=Number(el.value));bindValue(root,'#enemy-damage','change',el=>enemy.damage=Number(el.value));bindValue(root,'#enemy-armor','change',el=>enemy.armor=Number(el.value));bindValue(root,'#enemy-speed','change',el=>enemy.speed=Number(el.value));bindValue(root,'#enemy-xp','change',el=>enemy.xp=Number(el.value));bindValue(root,'#enemy-gold','change',el=>{enemy.gold=el.value.split(/[–-]/).map(Number)});
 $$('[data-drop]',root).forEach(input=>input.onchange=()=>{enemy.drops[Number(input.dataset.drop)].chance=Number(input.value);markDirty()});$$('[data-remove-drop]',root).forEach(button=>button.onclick=()=>{enemy.drops.splice(Number(button.dataset.removeDrop),1);markDirty();renderEnemyPanel()});$('#add-drop').onclick=()=>{enemy.drops.push({name:`Neuer Drop ${enemy.drops.length+1}`,chance:10});markDirty();renderEnemyPanel()}
}
function ensureAnimation(enemyId){if(!project.animations[enemyId])project.animations[enemyId]={sequences:[{name:'Idle',count:3,done:0},{name:'Start Walking',count:2,done:0},{name:'Walking',count:5,done:0},{name:'Stop Walking',count:2,done:0},{name:'Attack 1',count:4,done:0}],frames:{}};return project.animations[enemyId]}
function renderAnimationPanel(){const root=$('#tab-animation'),enemy=project.enemies.find(e=>e.id===selectedEnemyId),animation=ensureAnimation(enemy.id),done=animation.sequences.reduce((s,a)=>s+a.done,0),total=animation.sequences.reduce((s,a)=>s+a.count,0);root.innerHTML=`<div class="animation-summary"><div><strong>${done} von ${total} Bildern fertig</strong><span>${animation.sequences.length} Sequenzen</span></div><progress max="${total}" value="${done}"></progress></div>${animation.sequences.map(s=>`<div class="animation-card"><strong>${s.name}</strong><span>${s.done}/${s.count} Bilder</span></div>`).join('')}<button id="open-animation" class="primary wide">Design Studio öffnen</button><button id="add-attack" class="wide">+ Weitere Attacke</button>`;$('#open-animation').onclick=openAnimationDialog;$('#add-attack').onclick=()=>{const attacks=animation.sequences.filter(s=>s.name.startsWith('Attack')).length+1;animation.sequences.push({name:`Attack ${attacks}`,count:4,done:0});markDirty();renderAnimationPanel()}}
function renderInspector(){renderSpawnPanel();renderEnemyPanel();renderAnimationPanel();const spawn=project.spawns.find(s=>s.id===selectedSpawnId),enemy=project.enemies.find(e=>e.id===selectedEnemyId);$('#inspector-title').textContent=spawn?.name||enemy?.name||'Nichts ausgewählt'}
function renderAll(){renderEnemyList();renderWorld();renderInspector()}
function setTool(next){tool=next;$$('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));$('#status-tool').textContent={select:'Auswahl',monster:'Monster platzieren',zone:'Monsterzone',erase:'Löschen',pan:'Hand'}[tool];$('#placement-banner').hidden=!['monster','zone'].includes(tool);if(!$('#placement-banner').hidden)$('#placement-text').textContent=`${project.enemies.find(e=>e.id===selectedEnemyId).name} in einen Kartenabschnitt setzen`}
function readSources(){const list=[];try{const saved=JSON.parse(localStorage.getItem(QUEST_STORAGE_KEY)||'null');if(saved?.project?.world)list.push({label:'Prototyp 04 · NPCs & Quests',meta:`${saved.project.world.sections.length} Abschnitte · ${saved.project.npcs?.length||0} NPCs`,world:saved.project.world,npcs:saved.project.npcs||[]})}catch{}try{const saved=JSON.parse(localStorage.getItem(WORLD_STORAGE_KEY)||'null');if(saved?.world)list.push({label:'Prototyp 03 · Welt-Builder',meta:`${saved.world.sections.length} Abschnitte · ${saved.world.portals.length} Portale`,world:saved.world,npcs:[]})}catch{}try{const maps=JSON.parse(localStorage.getItem(MAP_LIBRARY_KEY)||'[]');for(const map of maps)if(map?.state?.map)list.push({label:`Prototyp 02 · ${map.name}`,meta:`${map.state.map.columns}×${map.state.map.rows} Tiles`,world:{version:2,name:map.name,sections:[{id:`map-${map.id}`,sourceMapId:map.id,name:map.name,x:3500,y:2200,mapState:map.state}],portals:[],spawn:null},npcs:[]})}catch{}return list}
function openWorldDialog(){const sources=readSources();$('#world-sources').innerHTML=sources.length?sources.map((source,i)=>`<article class="source-card"><strong>${source.label}</strong><span>${source.meta}</span><button data-source="${i}" class="primary">Übernehmen</button></article>`).join(''):'<div class="empty-list">Noch keine Daten gefunden. Speichere zuerst eine Map in Prototyp 02 oder eine Welt in Prototyp 03.</div>';$$('[data-source]').forEach(button=>button.onclick=()=>{const source=sources[Number(button.dataset.source)];project.world=clone(source.world);project.npcs=clone(source.npcs);project.source=source.label;$('#world-dialog').close();renderAll();requestAnimationFrame(centerWorld);toast('Welt übernommen')});$('#world-dialog').showModal()}
function centerWorld(){if(!project.world?.sections.length)return;const left=Math.min(...project.world.sections.map(s=>s.x)),right=Math.max(...project.world.sections.map(s=>s.x+mapWidth(s))),top=Math.min(...project.world.sections.map(s=>s.y)),bottom=Math.max(...project.world.sections.map(s=>s.y+mapHeight(s)));viewport.scrollTo({left:(left+right)*zoom/2-viewport.clientWidth/2,top:(top+bottom)*zoom/2-viewport.clientHeight/2})}
let animationSequence=0,animationFrame=0,paintTool='draw',painting=false;
const pixelCanvas=$('#pixel-canvas'),pixelContext=pixelCanvas.getContext('2d'),GRID=16;
function basePixels(){const pixels=Array.from({length:GRID},()=>Array(GRID).fill(null));['................','................','.....GGGG.......','...GGGGGGGG.....','..GGGGGGGGGG....','.GGGGGGGGGGGG...','.GGGLLGGLLGGG...','.GGGDDGGDDGGG...','.GGGGGGGGGGGG...','.GGGGGGGGGGGG...','.GGGGGGGGGGGG...','GGGGGGGGGGGGGG..','GGGGGGGGGGGGGG..','GGGGGGGGGGGGGG..','.GGGG....GGGG...','................'].forEach((row,y)=>[...row].forEach((cell,x)=>pixels[y][x]=cell==='G'?'#88b95a':cell==='L'?'#d7e684':cell==='D'?'#344532':null));return pixels}
function frameKey(){return `${animationSequence}:${animationFrame}`}
function currentPixels(){const animation=ensureAnimation(selectedEnemyId);if(!animation.frames[frameKey()])animation.frames[frameKey()]=basePixels();return animation.frames[frameKey()]}
function drawPixels(){const size=pixelCanvas.width/GRID,pixels=currentPixels();pixelContext.fillStyle='#cbd1c7';pixelContext.fillRect(0,0,pixelCanvas.width,pixelCanvas.height);if($('#show-ghost').checked){pixelContext.globalAlpha=.13;pixelContext.fillStyle='#a05f59';pixelContext.beginPath();pixelContext.ellipse(256+(animationFrame%3-1)*18,286+(animationFrame%2)*12,155,130,0,0,Math.PI*2);pixelContext.fill();pixelContext.globalAlpha=1}for(let y=0;y<GRID;y++)for(let x=0;x<GRID;x++)if(pixels[y][x]){pixelContext.fillStyle=pixels[y][x];pixelContext.fillRect(x*size,y*size,size,size)}pixelContext.strokeStyle='#5e685f33';for(let i=0;i<=GRID;i++){pixelContext.beginPath();pixelContext.moveTo(i*size,0);pixelContext.lineTo(i*size,512);pixelContext.stroke();pixelContext.beginPath();pixelContext.moveTo(0,i*size);pixelContext.lineTo(512,i*size);pixelContext.stroke()}}
function renderAnimationDialog(){const animation=ensureAnimation(selectedEnemyId),sequence=animation.sequences[animationSequence];$('#animation-kicker').textContent=`${sequence.name} · Bild ${animationFrame+1} von ${sequence.count}`;$('#animation-title').textContent=`${sequence.name} ${animationFrame+1}`;$('#sequence-list').innerHTML=animation.sequences.map((s,i)=>`<button class="sequence-group ${i===animationSequence?'active':''}" data-sequence="${i}"><span>${s.name}</span><b>${s.done}/${s.count}</b></button>`).join('');$$('[data-sequence]',$('#sequence-list')).forEach(button=>button.onclick=()=>{animationSequence=Number(button.dataset.sequence);animationFrame=0;renderAnimationDialog()});$('#ghost-preview').style.transform=`translateY(${animationFrame%2?8:0}px) scale(${1+(animationFrame%2)*.06},${1-(animationFrame%2)*.04})`;drawPixels()}
function openAnimationDialog(){animationSequence=0;animationFrame=0;renderAnimationDialog();$('#animation-dialog').showModal()}
function moveAnimation(delta,complete=false){const animation=ensureAnimation(selectedEnemyId),sequence=animation.sequences[animationSequence];if(complete)sequence.done=Math.max(sequence.done,animationFrame+1);if(delta>0&&animationFrame===sequence.count-1){if(animationSequence<animation.sequences.length-1){animationSequence++;animationFrame=0;toast(`${sequence.name} abgeschlossen`)}else toast('Alle Bilder abgeschlossen')}else animationFrame=Math.max(0,Math.min(sequence.count-1,animationFrame+delta));markDirty();renderAnimationDialog();renderAnimationPanel()}
function paint(event,erase=false){const rect=pixelCanvas.getBoundingClientRect(),x=Math.floor((event.clientX-rect.left)/rect.width*GRID),y=Math.floor((event.clientY-rect.top)/rect.height*GRID);if(x<0||y<0||x>=GRID||y>=GRID)return;currentPixels()[y][x]=erase||paintTool==='erase'?null:$('#paint-color').value;markDirty();drawPixels()}
pixelCanvas.onpointerdown=event=>{painting=true;pixelCanvas.setPointerCapture(event.pointerId);paint(event,event.button===2)};pixelCanvas.onpointermove=event=>{if(painting)paint(event,event.buttons===2)};pixelCanvas.onpointerup=()=>painting=false;pixelCanvas.oncontextmenu=event=>event.preventDefault();$$('.paint-tool').forEach(button=>button.onclick=()=>{$$('.paint-tool').forEach(b=>b.classList.remove('active'));button.classList.add('active');paintTool=button.dataset.paint});$('#show-ghost').onchange=drawPixels;$('#previous-frame').onclick=()=>moveAnimation(-1);$('#skip-frame').onclick=()=>moveAnimation(1);$('#complete-frame').onclick=()=>moveAnimation(1,true);$('.close-animation').onclick=()=>$('#animation-dialog').close();
function saveProject(){localStorage.setItem(PROJECT_STORAGE_KEY,JSON.stringify({updatedAt:Date.now(),project}));$('#save-state').textContent='Lokal gespeichert';toast('Monster-Projekt gespeichert')}
function loadProject(){try{const saved=JSON.parse(localStorage.getItem(PROJECT_STORAGE_KEY)||'null');if(!saved?.project)throw new Error();project=clone(saved.project);project.animations||={};project.npcs||=[];selectedEnemyId=project.enemies[0]?.id||null;selectedSpawnId=null;renderAll();requestAnimationFrame(centerWorld);toast('Monster-Projekt geladen')}catch{toast('Noch kein Monster-Projekt gespeichert')}}
function exportProject(){const blob=new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${(project.world?.name||'idlekin').replace(/[^a-z0-9äöüß-]+/gi,'-').toLowerCase()}-monster.json`;link.click();URL.revokeObjectURL(url);toast('Projekt exportiert')}
function playProject(){if(!project.world?.sections.length)return toast('Lade zuerst eine Welt');localStorage.setItem(PLAYTEST_KEY,JSON.stringify({source:'05',label:project.world.name||'Monster-Test',returnUrl:'../05-monster-boss-editor/',project:clone(project)}));location.href='../01-side-view-movement/'}
$$('.tool').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$('#zoom').onchange=()=>{zoom=Number($('#zoom').value);worldElement.style.zoom=zoom};$('#load-world').onclick=$('#empty-load').onclick=openWorldDialog;$('#load-project').onclick=loadProject;$('#play-project').onclick=playProject;$('#save-project').onclick=saveProject;$('#export-project').onclick=exportProject;$('.close-dialog').onclick=()=>$('#world-dialog').close();$('#center-world').onclick=centerWorld;$('#cancel-placement').onclick=()=>setTool('select');$('#show-portals').onchange=renderWorld;$('#show-npcs').onchange=renderWorld;
$('#add-enemy').onclick=()=>{const enemy={...clone(ENEMIES[0]),id:`enemy-${Date.now()}`,name:`Neuer Gegner ${project.enemies.length+1}`,drops:[]};project.enemies.push(enemy);selectedEnemyId=enemy.id;selectedSpawnId=null;markDirty();renderAll();$('.tab[data-tab="enemy"]').click();toast('Neuer Gegner angelegt')};
$$('.tab').forEach(button=>button.onclick=()=>{$$('.tab').forEach(b=>b.classList.remove('active'));button.classList.add('active');$$('.tab-panel').forEach(panel=>panel.hidden=true);$(`#tab-${button.dataset.tab}`).hidden=false});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){if($('#animation-dialog').open)$('#animation-dialog').close();else setTool('select')}if(!event.ctrlKey&&!event.metaKey){const key=event.key.toLowerCase();if({v:'select',m:'monster',z:'zone',e:'erase',h:'pan'}[key])setTool({v:'select',m:'monster',z:'zone',e:'erase',h:'pan'}[key])}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();saveProject()}});
worldElement.style.zoom=zoom;
try{const saved=JSON.parse(localStorage.getItem(PROJECT_STORAGE_KEY)||'null');if(saved?.project){project=clone(saved.project);project.animations||={};project.npcs||=[];selectedEnemyId=project.enemies[0]?.id||null}else{const source=readSources()[0];if(source){project.world=clone(source.world);project.npcs=clone(source.npcs);project.source=source.label}}}catch{}
renderAll();setTimeout(centerWorld,100);
