import './style.css';
import type { Area, CharacterSnapshot, MovementInput, ServerMessage } from '@idlekin/shared';
import { Connection } from './net/connection.js'; import { store } from './net/store.js'; import { Keyboard } from './input/keyboard.js'; import { Prediction } from './net/prediction.js'; import { Renderer } from './render/renderer.js'; import { flashTransition } from './scenes/areaTransition.js';

const canvas=document.querySelector<HTMLCanvasElement>('#game')!;const dialog=document.querySelector<HTMLDialogElement>('#login')!;const nameInput=document.querySelector<HTMLInputElement>('#player-name')!;const errorOutput=document.querySelector<HTMLOutputElement>('#login-error')!;const connection=new Connection();const keyboard=new Keyboard();const prediction=new Prediction();const renderer=new Renderer(canvas);
dialog.showModal();
let area:Area|undefined;let character:CharacterSnapshot|undefined;let sequence=0;let tick=0;let currentInput:MovementInput={left:false,right:false,jump:false,jumpPressed:false,down:false};
store.subscribe(state=>{document.querySelector('#status')!.textContent=state.status;document.querySelector('#latency')!.textContent=`${state.latency.toFixed(0)} ms`;document.querySelector('#area')!.textContent=state.area?.name??'–';document.querySelector('#identity')!.textContent=state.player?`${state.player.name} · ${state.character?.name??'–'}`:'–';});
connection.onMessage((message:ServerMessage)=>{if(message.t==='authOk'){store.patch({player:message.player});character=message.player.characters[0];if(character)connection.send({t:'subscribe',characterId:character.id});dialog.close();}else if(message.t==='authFail'){errorOutput.value=message.reason;localStorage.removeItem('idlekin-token');}else if(message.t==='state'){character=message.state;area=message.area;store.patch({character,area});prediction.reset(character.x,character.y);renderer.snap(prediction.state,area);}else if(message.t==='moveAck'&&area)prediction.reconcile(message.sequence,message.state,area);else if(message.t==='area'){character=message.state;area=message.area;store.patch({character,area});prediction.reset(character.x,character.y);renderer.snap(prediction.state,area);flashTransition(canvas);}else if(message.t==='error')console.warn(message.message);});
document.querySelector<HTMLFormElement>('#login form')!.addEventListener('submit',async event=>{event.preventDefault();errorOutput.value='';try{const response=await fetch('/auth/dev',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:nameInput.value})});if(!response.ok)throw new Error((await response.json() as {error?:string}).error??'Anmeldung fehlgeschlagen');const value=await response.json() as {token:string};localStorage.setItem('idlekin-token',value.token);connection.connect(value.token);}catch(error){errorOutput.value=error instanceof Error?error.message:'Anmeldung fehlgeschlagen';}});
const saved=localStorage.getItem('idlekin-token');if(saved)connection.connect(saved);
let accumulator=0,last=performance.now();const step=1/60;
function frame(now:number){const elapsed=Math.min((now-last)/1000,.25);last=now;accumulator+=elapsed;while(accumulator>=step){if(area&&character){currentInput=keyboard.sample();prediction.predict(currentInput,area);tick++;if(tick%3===0){sequence++;prediction.record(sequence,currentInput);connection.send({t:'move',characterId:character.id,sequence,input:currentInput});}if(keyboard.takePortal()){const portal=area.portals.find(value=>Math.abs(prediction.state.x+6-value.position.x)<=32);if(portal)connection.send({t:'enterPortal',characterId:character.id,portalId:portal.id});}}accumulator-=step;}if(area&&prediction.state)renderer.render(prediction.state,prediction.previous,area,accumulator/step,elapsed,keyboard.debug);requestAnimationFrame(frame);}requestAnimationFrame(frame);
